### ISSUE TITLE
Write functions to launch `Kubernetes` pods.

### ISSUE THREAD

**Issue by RobbieMcKinstry** [alligrader/autograder#2]
# Abstract

Once the EventWatcher (https://github.com/alligrader/autograder/issues/1) identifies the kind of event we're receiving, it needs to launch a pod on Kubernetes to run the Job.

# Intro

Presently:

1. Our [Jobs repo](https://github.com/alligrader/jobs) contains the definition of a Job.
1. Our [autograder repo](https://github.com/alligrader/autograder) receives a webhook which identifies which kind of event it's received.

Next, we need to specify what should happen when an event is received. In our case, we need to launch a Docker container onto Kubernetes when a `PullRequest` or `Push` event is received. The container we launch doesn't actually matter for now. (Maybe I'll have the time to set up the correct container before you get started on this issue.) As long as we launch any container, we can easily switch to launching the right container when we get a little further along.

We need to use the Kubernetes API to submit a `Batch` job. This `Batch` job is not to be confused with our `Job` type or our `jobs` repo. These are conceptually similar but they are all typed slightly differently: the first is a Kubernetes pod, the second is repo name containing any of our different individual jobs plus the code to execute them, and the third is a particular type we've implemented in Go. Wholistically, the word "job" is being used to the same effect in which case: we have a ball of code we want to execute, and it should halt.

# Prior Work

I wrote a program to launch a Kubernetes `Batch` job a few months ago. Unfortunately, I used a **bad** library at the time, the `unversioned` Kubernetes API lib. This was a dumb mistake, and as a result we can't use the code I wrote previously. However, it may be useful to look over just to see a complete function. It also makes use of a number of **good** libraries, so that could be helpful as well. Here's a link to the [full source code](https://github.com/RobbieMcKinstry/kubernetes-batch/blob/master/main.go).

However, I also found what looks like a good example using a good library. This doesn't make sure of the `Batch` job functionality of Kubernetes, but it does give you a starting point for authenticating to the Kubernetes cluster. [Here's a link](https://github.com/kubernetes/client-go/blob/master/examples/out-of-cluster/main.go) to that code. Here's a link to [the documentation](https://godoc.org/k8s.io/client-go/rest#Config) for that library. Note that it only provides the auth methods, and you'll have to dig into the other libs imported in the example to see their documentation. Still, it should be enough to get you started.

Once you've launched a `Batch` job, you'll need to confirm that the job ran. You can either do this via the command line with `kubectl get pods --all` or `kubectl log ----` with the job ID, or you can use the web UI. To use the web UI, ssh into the Vagrant box with `vagrant ssh`, then run `rake k8s`, which should start serving the web UI. Then, you can visit `http://localhost:8001/ui` to view the Kubernetes dashboard.

You might want to play around with the dashboard before anything else. That might give you a good idea as to what it's like to launch a Batch job.

# TODOs

Prereq: https://github.com/alligrader/autograder/issues/1
- [ ] Connect to the Kubernetes cluster. The SSL files are located either [here](https://github.com/alligrader/gradebook-api/tree/master/ssl) or at `gradebook-api/.deploy/coreos-kubernetes/single-node/ssl`. Which it is depends on your configuration. Might need to try both.
- [ ] Get the Batch client set
- [ ] Set up the options to use a particular pod. (I'm going to make a pod available for our purposes on DockerHub at a later time. Any pod will work for now.) [Here's an example](https://github.com/RobbieMcKinstry/kubernetes-batch/blob/master/batch.yaml) batch pod template.
- [ ] Launch the job and confirm there is no error
- [ ] Confirm that the pod executed in the web UI (screenshot it if you can! 😸 )
